name: generate-snake

on:
  schedule: # Exécution automatique chaque jour à minuit UTC
    - cron: "0 0 * * *"
  workflow_dispatch: # Permet de lancer manuellement si besoin

permissions:
  contents: write   # 🔑 Donne le droit au bot d'écrire dans ton repo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create dist folder
        run: mkdir -p dist

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: chayma403
          outputs: dist/snake.svg

      - name: Verify generated file
        run: ls -la dist/

      - name: Push Snake to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
